name: Publish

on:
  push:
    tags: 
      - '*'

jobs:
  publish-npm:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
        continue-on-error: false
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
